Fix argument to OpenSCAD2Dgeom.edgestofaces
OpenSCAD2Dgeom.edgestofaces expects a list of edges, not wires.
Without this change, and with certain input geometry, edgestofaces
fails because it (silently) catches the following exception:

  Traceback (most recent call last):
    File "/home/foo/.FreeCAD/Mod/pcb/PCBboard.py", line 201, in execute
      face = OpenSCAD2Dgeom.edgestofaces(fp.Border.Shape.Wires)
    File "/home/foo/.FreeCAD/Mod/pcb/OpenSCAD2Dgeom.py", line 382, in edgestofaces
      wires = edgestowires(edges,eps)
    File "/home/foo/.FreeCAD/Mod/pcb/OpenSCAD2Dgeom.py", line 332, in edgestowires
      w2=superWireReverse(debug,tobeclosed)
    File "/home/foo/.FreeCAD/Mod/pcb/OpenSCAD2Dgeom.py", line 470, in superWireReverse
      if isinstance(curr[0].Curve,(Part.LineSegment, Part.Line)):
  <class 'AttributeError'>: 'Part.Wire' object has no attribute 'Curve'